export enum BlockType {
  SearchList = 3,
  SearchChocie = 4,
  LogKeyword = 5,
  Report = 6,
  QueryInput = 7,
  OperationOutput = 8,
  SelectOutput = 9,
  LogOutput = 10,
  WORKER = 11,
  DEVELOPER = 12,
  LogDate = 13,
  LogLevel = 14,
  CommitResult = 15,
  CommitError = 16,
  RollbackOutput = 1035,
}
