spring:
  # DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mes?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://k9b201a.p.ssafy.io:3306/mes?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ksol
    password: ksol1117
#    url: jdbc:mysql://localhost:3306/mes?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        discriminator:
          ignore_explicit_for_joined: true
    .open-in-view: false

  # redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # 이메일
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: B201MESC
  #    password: szwj gsio ejxo zxqp
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          timeout: 5000
  #          starttls:
  #            enable: true
  #  thymeleaf:
  #    cache: false

  #  firebase:
  #    serviceAccountPath: path/to/serviceAccountKey.json
  #  security:
  #    user:
  #      name: admin
  #      password: admin

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 50MB
#      max-request-size: 50MB

# JPA log
logging:
  level:
    com.ksol.mes: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# jwt secret key 설정
jwt:
  key: YourewaitingforatrainAtrainthatwilltakeyoufarawayYouknowwhereyouhope

server:
  port: 8081
  ec2-url: https://
