spring:
  jpa:
    database: mysql   # ?? ?? ??
    open-in-view: true
    hibernate:
      ddl-auto: none
      #ddl-auto: none
#      show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  config:
    import:
      - db.yml

logging:
  level:
    mesc: debug

# ? ?? ?? ??
# true? default ??????? false? ??!!
decorator:
  datasource:
    p6spy:
      enable-logging: true
